name: Crawler

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:
  schedule:
  - cron: '0 14 * * *'
  workflow_dispatch:

jobs:
  checkout_source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          repository: ietf-ribose/ieee-rawbib
          token: ${{ secrets.IETF_BIB_BOT_PAT }}
          path: ieee-rawbib
  crawl:
    uses: relaton/support/.github/workflows/crawler.yml@master
    with:
      override-files: |
        https://raw.githubusercontent.com/ietf-tools/bibxml-service/main/Gemfile=Gemfile
      args: ${{ github.event.inputs.args }}
      commit-indexes: false
