name: Crawler

on:
  push:
    branches: [ master, main ]
    tags: [ v* ]
  pull_request:
  schedule:
  - cron: '0 14 * * *'
  workflow_dispatch:

env:
  token: "test"

jobs:
  crawl:
    uses: relaton/support/.github/workflows/crawler.yml@master
    with:
      override-files: |
        https://raw.githubusercontent.com/ietf-tools/bibxml-service/main/Gemfile=Gemfileg
      args: ${{ github.event.inputs.args }}
      commit-indexes: false
    secrets: inherit

